[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "devutilitytool"
version = "0.1.0"
description = "Developer productivity CLI built with Python and Typer."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Muhammad Ahmed Bajwa" }
]

dependencies = [
    "typer>=0.16.0"
]

[project.scripts]
devtool = "src.app:app"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["src*"]